"""empty message

Revision ID: 1c0512713361
Revises: fbeea2d34ea1
Create Date: 2020-12-17 10:06:58.119053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0512713361'
down_revision = 'fbeea2d34ea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('owner_avatar_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'owner_avatar_url')
    # ### end Alembic commands ###
