"""empty message

Revision ID: 1c18e8352346
Revises: a28cf1e1a373
Create Date: 2021-07-30 16:52:13.674066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c18e8352346'
down_revision = 'a28cf1e1a373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'order')
    # ### end Alembic commands ###
