"""empty message

Revision ID: 28036c4e98dc
Revises: b426d38ac5d5
Create Date: 2021-07-28 19:30:01.412802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28036c4e98dc'
down_revision = 'b426d38ac5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('like_association_id', sa.Integer(), nullable=True),
    sa.Column('comment_association_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_association_id'], ['comment_association.id'], ),
    sa.ForeignKeyConstraint(['like_association_id'], ['like_association.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id')
    )
    op.add_column('albums', sa.Column('comment_association_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'albums', 'comment_association', ['comment_association_id'], ['id'])
    op.add_column('media', sa.Column('series_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'media', 'series', ['series_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_column('media', 'series_id')
    op.drop_constraint(None, 'albums', type_='foreignkey')
    op.drop_column('albums', 'comment_association_id')
    op.drop_table('series')
    # ### end Alembic commands ###
