"""Add song_writer to media

Revision ID: 34724025a7d9
Revises: 25a58a1c2898
Create Date: 2020-12-13 19:57:36.502975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34724025a7d9'
down_revision = '25a58a1c2898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('song_writer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'song_writer')
    # ### end Alembic commands ###
