"""empty message

Revision ID: 3e07b8561bde
Revises: 8055b0f9fd00
Create Date: 2021-04-14 23:02:25.892655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e07b8561bde'
down_revision = '8055b0f9fd00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slider_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slider_id', sa.Integer(), nullable=False),
    sa.Column('slider_item_id', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['slider_id'], ['sliders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slider_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slider_items')
    # ### end Alembic commands ###
