"""Add record_label to media

Revision ID: 593676e1e155
Revises: 34724025a7d9
Create Date: 2020-12-13 19:58:56.641042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593676e1e155'
down_revision = '34724025a7d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('record_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'record_label')
    # ### end Alembic commands ###
