"""Add release_date to media

Revision ID: 6eea8bfd3748
Revises: 593676e1e155
Create Date: 2020-12-13 20:01:21.566502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eea8bfd3748'
down_revision = '593676e1e155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('release_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'release_date')
    # ### end Alembic commands ###
