"""Added many to many btn media and genre

Revision ID: 7684c0fca0de
Revises: d83f5dd29186
Create Date: 2021-01-16 15:32:11.329723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7684c0fca0de'
down_revision = 'd83f5dd29186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre_media',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre_media')
    # ### end Alembic commands ###
