"""empty message

Revision ID: 8055b0f9fd00
Revises: 001bbc33a434
Create Date: 2021-04-14 15:52:39.209675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8055b0f9fd00'
down_revision = '001bbc33a434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slider_pictures')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slider_pictures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['slider_id'], ['sliders.id'], name='slider_pictures_slider_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='slider_pictures_pkey')
    )
    # ### end Alembic commands ###
