"""Added cover_url to users

Revision ID: 84be2faa347e
Revises: 5b0a4e218f98
Create Date: 2021-01-18 07:44:53.427744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84be2faa347e'
down_revision = '5b0a4e218f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cover_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cover_url')
    # ### end Alembic commands ###
