"""empty message

Revision ID: 90af119ff762
Revises: 1c18e8352346
Create Date: 2021-08-01 10:27:01.349057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90af119ff762'
down_revision = '1c18e8352346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('comment_association_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('like_association_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'like_association', ['like_association_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'comment_association', ['comment_association_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'like_association_id')
    op.drop_column('posts', 'comment_association_id')
    # ### end Alembic commands ###
