"""added a relationship between genres and series

Revision ID: a28cf1e1a373
Revises: 28036c4e98dc
Create Date: 2021-07-28 20:54:41.608497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28cf1e1a373'
down_revision = '28036c4e98dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre_series',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], )
    )
    op.add_column('series', sa.Column('cover_url', sa.String(), nullable=True))
    op.add_column('series', sa.Column('trailer_url', sa.String(), nullable=True))
    op.alter_column('series', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('series', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('series', 'trailer_url')
    op.drop_column('series', 'cover_url')
    op.drop_table('genre_series')
    # ### end Alembic commands ###
