"""Added publish column

Revision ID: a6fc9a31a3be
Revises: 1a1a70ab39c6
Create Date: 2020-12-12 18:33:06.616993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6fc9a31a3be'
down_revision = '1a1a70ab39c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('publish', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'publish')
    # ### end Alembic commands ###
