"""empty message

Revision ID: aa891caec256
Revises: e24d40d4d870
Create Date: 2021-04-23 15:40:44.758896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa891caec256'
down_revision = 'e24d40d4d870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sliders', sa.Column('aspect_ratio_x', sa.Integer(), nullable=True))
    op.add_column('sliders', sa.Column('aspect_ratio_y', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sliders', 'aspect_ratio_y')
    op.drop_column('sliders', 'aspect_ratio_x')
    # ### end Alembic commands ###
