"""Created some json fields

Revision ID: b426d38ac5d5
Revises: 0e5fffc7cc8d
Create Date: 2021-07-24 13:01:51.683503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b426d38ac5d5'
down_revision = '0e5fffc7cc8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('posts', sa.Column('videos', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'videos')
    op.drop_column('posts', 'images')
    # ### end Alembic commands ###
