"""empty message

Revision ID: c0558fd34fc5
Revises: c0e7cc5c8e34
Create Date: 2020-12-14 11:05:05.391805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0558fd34fc5'
down_revision = 'c0e7cc5c8e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_user_favourites',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('media_user_history',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('plays', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_table('media_user')
    op.drop_table('history_media')
    op.drop_table('history')
    op.drop_table('favourites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('favourites_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favourites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favourites_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('history',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('history_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='history_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='history_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('history_media',
    sa.Column('history_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plays', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['history.id'], name='history_media_history_id_fkey'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name='history_media_media_id_fkey')
    )
    op.create_table('media_user',
    sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('favourite_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['favourite_id'], ['favourites.id'], name='media_user_favourite_id_fkey'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name='media_user_media_id_fkey')
    )
    op.drop_table('media_user_history')
    op.drop_table('media_user_favourites')
    # ### end Alembic commands ###
