"""Add favourites

Revision ID: c0e7cc5c8e34
Revises: 6eea8bfd3748
Create Date: 2020-12-14 09:42:02.251027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e7cc5c8e34'
down_revision = '6eea8bfd3748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('media_user', sa.Column('favourite_id', sa.Integer(), nullable=False))
    op.drop_constraint('media_user_user_id_fkey', 'media_user', type_='foreignkey')
    op.create_foreign_key(None, 'media_user', 'favourites', ['favourite_id'], ['id'])
    op.drop_column('media_user', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_user', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'media_user', type_='foreignkey')
    op.create_foreign_key('media_user_user_id_fkey', 'media_user', 'users', ['user_id'], ['id'])
    op.drop_column('media_user', 'favourite_id')
    op.drop_table('favourites')
    # ### end Alembic commands ###
