"""Add modified on Comment model

Revision ID: d83f5dd29186
Revises: 4ce19971b7ec
Create Date: 2021-01-05 23:47:32.012838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83f5dd29186'
down_revision = '4ce19971b7ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('modified', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'modified')
    # ### end Alembic commands ###
