"""Transformed the comment table to be a Polymorphic table

Revision ID: eaf429afa5d4
Revises: c9ca3e10509b
Create Date: 2021-06-14 11:09:51.199797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf429afa5d4'
down_revision = 'c9ca3e10509b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dicriminator', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comments', sa.Column('association_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_media_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'comment_association', ['association_id'], ['id'])
    op.drop_column('comments', 'media_id')
    op.add_column('media', sa.Column('comment_association_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'media', 'comment_association', ['comment_association_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_column('media', 'comment_association_id')
    op.add_column('comments', sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_media_id_fkey', 'comments', 'media', ['media_id'], ['id'])
    op.drop_column('comments', 'association_id')
    op.drop_table('comment_association')
    # ### end Alembic commands ###
