"""Add many to many btn album and genres

Revision ID: f2e03ba79fb2
Revises: 7684c0fca0de
Create Date: 2021-01-16 15:58:58.580773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e03ba79fb2'
down_revision = '7684c0fca0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre_album',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], )
    )
    op.drop_column('albums', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('genre_album')
    # ### end Alembic commands ###
