"""Added admin_id to users table

Revision ID: fa23fc78f0cc
Revises: a6fc9a31a3be
Create Date: 2020-12-13 00:02:18.351779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa23fc78f0cc'
down_revision = 'a6fc9a31a3be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin_id')
    # ### end Alembic commands ###
